Tweaks to use jupyterlab-hdf as standalone web app
jupyterlab/jupyterlab-hdf5 pull request #38
Opened 2020-09-17 09:03 UTC by loichuder

A small change to the `_load_handlers` signature to make it less dependent on the NotebookApp format.

This allows to to serve the handler with a standalone Tornado App instead of a JupyterLab instance:
```
import os
import tornado
from jupyterlab_hdf import _load_handlers

if __name__ == "__main__":
    app = tornado.web.Application()
    _load_handlers(os.path.abspath(os.path.curdir), app)
    app.listen(8888)
    tornado.ioloop.IOLoop.current().start()
```

2020-09-17 09:04 UTC, loichuder commented on jupyterlab_hdf/__init__.py
> +    base_url = web_app.settings["base_url"] if "base_url" in web_app.settings else "/"
Introduced as fallback to avoid not obvious `404` when `base_url` is not present in the app settings.

2020-09-17 09:05 UTC, loichuder commented on jupyterlab_hdf/__init__.py
> +    _load_handlers(nb_server_app.notebook_dir, nb_server_app.web_app)
Pass `notebook_dir` rather than the `app`

2020-10-12 16:44 UTC, telamonian requested changes
Nice work. My only niggle is that you need to change the quotation marks back to single quotes, to be consistent with the rest of the project

2020-10-13 07:03 UTC, telamonian approved these changes
LGTM!

2020-10-13 07:03 UTC, merged