Complex is now serialized as two value array rather than str
jupyterlab/jupyterlab-hdf5 pull request #82
Opened 2021-02-23 17:02 UTC by loichuder

2021-03-03 04:47 UTC, telamonian commented
This PR seems good like a good idea overall. I'm a touch worried though about it will interact with the existing shape inference and shape coercion code. Basically, I'm concerned that something will end up treating eg a `(3, 3, 3)` array of complex as a `(3, 3, 3, 2)` array of reals.

I'll trace through the code until I'm satisfied this won't cause an issue (or until I find an issue). Alternatively, I suppose we could firm up the unittests for shape inference and coercion instead. That would probably also be sufficient to ease my worried mind

2021-03-05 16:02 UTC, loichuder commented
I checked and everything works as intended for complex scalars, 1D arrays and nD arrays.

I think it stems from the fact that the shape inference and shape coercion code uses the NumPy arrays that have the appropriate dimensions and have no knowledge about how the value is then serialized.

2021-03-05 17:06 UTC, telamonian requested changes
> I think it stems from the fact that the shape inference and shape coercion code uses the NumPy arrays that have the appropriate dimensions and have no knowledge about how the value is then serialized.

Sounds about right. If you add whatever update is needed to properly display these 2-tuple complexes on the frontend, we can call this PR done.

I would also like to see at least one unittest that covers the `min_ndim` query parameter, but I wouldn't say that's a blocker for this PR

2021-03-08 11:20 UTC, loichuder reviewed
Formatting lead to heavy diff. I tried to underline the main changes when needed.

2021-03-08 11:20 UTC, loichuder commented on .eslintrc.js
> +    '@typescript-eslint/no-floating-promises': ['warn', { ignoreVoid: true }],
The `pre-commit` hook was preventing me from commiting `dataset.ts` due to this. I set it to warning until we fix the errors.

2021-03-08 11:20 UTC, loichuder commented on .eslintrc.js
> +    node: true,
Without this, `document` is treated as undef and `module` as well.

2021-03-08 11:20 UTC, loichuder commented on src/hdf.ts
> +): Promise<number[][] | Complex[][]> {
The main change is here

2021-03-08 11:20 UTC, loichuder commented on src/hdf.ts
> +      } catch (error) {} // eslint-disable-line no-empty
Again, I had to do this to make the pre-commit happy

2021-03-08 11:20 UTC, loichuder commented on src/dataset.ts
> +      return data;
Main change is here

2021-03-16 00:01 UTC, telamonian approved these changes
LGTM!

2021-03-16 00:02 UTC, merged